### ISSUE TITLE
usage instructions are not specific enough

### ISSUE THREAD

**Issue by soundyogi** [afuzzyllama/VoronoiDiagram#1]
hi! thanks for the lib.
I am struggling to use it though.

"To use, clone the code into a directory named 'VoronoiDiagram' in your Unreal project's plugin directory. Don't forget to add a public dependency to your project for the plugin, or else your Unreal project will not be able to find it.''

It would be nice if you could be more specific on how to add a public dependency for example.
Also, is this still working with UE4.1x?

Thanks!

**Comment by afuzzyllama** [comment]
You can add a public dependency to your project in the `Source/[ProjectName]/[ProjectName].Build.cs` you can find more information [here](https://wiki.unrealengine.com/An_Introduction_to_UE4_Plugins#Non-Game_Module)

I haven't used or updated this plugin since 2015 so I'm not sure it if works with the current version of the engine.
